### PR TITLE
handle the case where there are multiple headers with same name and are ...

### PR DESCRIPTION
**Pull request by nightshade427**
...numbers. (ex: there are two "age: 0" headers), example site that has this issue (http://www.sonosite.com)

### CODE REVIEW

**Comment by fukamachi** [comment]
Thank you for reporting.

However, is it okay to just ignore the previous value when it is a number?

> Multiple message-header fields with the same field-name may be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It must be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy must not change the order of these field values when a message is forwarded

> http://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.2.p.4

I think it also should be concatenated with a comma like string values. What do you think?

**Comment by nightshade427** [comment]
You can discard if its a number if you want. I wouldnt concat them as most instances I see it seems they intended to overright the previous value. Like the site indicated in the issue has "age: 0" twice and I think it should report the key "age" as 0 not "0, 0"

**Comment by nightshade427** [comment]
Feel free to reject this pull request and fix another way (but, I wouldnt concate). It just the above solved my use case for the site indicated :)

**Comment by fukamachi** [comment]
> Like the site indicated in the issue has "age: 0" twice and I think it should report the key "age" as 0 not "0, 0"

Yeah, it seems so.

>     Age = "Age" ":" age-value
>     age-value = delta-seconds
> Age values are non-negative decimal integers, representing time in
> seconds.
> http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.6

I think the site is doing something wrong. It can be avoided by checking the header-field is `Age` or not, but I'm not really fascinated at the approach.

**Comment by nightshade427** [comment]
Yeah it seems to me a mistake that the site is having two "age" headers but it would be nice in these cases if it fell back to using just one of them. Not all sites on web behave themselves as they should .. hehe

**Comment by fukamachi** [comment]
I fixed this at https://github.com/fukamachi/fast-http/commit/5fc45f310faddfb8b94a15e2aa8586a437530321. Though I know some web servers behave weirdly, I don't wanna add a special case in fast-http for now.

**Comment by nightshade427** [comment]
Yeah I understand just thought it would be nice to fall back and be graceful like curl handles the site above by ignoring numbers or replacing the previous header value if it was a number.

**Comment by nightshade427** [comment]
I'll pull latest and test. Thanks a bunch :)

**Comment by fukamachi** [comment]
Thank you, too :)

**Pull request closed without merging**
